# Benchmark map size
benchmark_nbr_rows: 400
benchmark_nbr_cols: 1000
gicp_benchmark_nbr_rows: 500
gicp_benchmark_nbr_cols: 500

# Point cloud downsampling (m)
downsampling_leaf_x: .2
downsampling_leaf_y: .2
downsampling_leaf_z: .1

# Bathy SLAM params
submap_size: 500 # nbr_pings per submap
add_gaussian_noise: false
online_LC_combine_overlapping_submaps: false
load_offline_LC: true
#offline_LC_folder: "/home/li/Documents/smarc_misc/SubmapsRegistration/bin/mission11-subset-test2-more-overlap/iterative-gicp-results-230118/"
offline_LC_folder: "/home/li/Documents/smarc_misc/SubmapsRegistration/bin/230210-mission11-navlab-smooth-map/offline-icp-results/"
#offline_LC_folder: "/home/li/Documents/smarc_misc/SubmapsRegistration/bin/230125-mission11-navlab-smooth/"
offline_LC_max_rms: 3.0
filter_non_adjacent_line_overlaps: false

# Submap overlaps
overlap_coverage: 0.8 # Reduce submap area to look for overlap by this factor

# GICP registration params (meters)
gicp_max_iterations: 20
gicp_max_correspondence_distance: 10
gicp_maximum_iterations: 200
gicp_maximum_optimizer_iterations: 20
gicp_transform_epsilon: 1e-4
gicp_euclidean_fitness_epsilon: 1e-5
gicp_ransac_iterations: 20
gicp_ransac_outlier_rejection_threshold: 0.5 
gicp_normal_use_knn_search: true
gicp_normal_search_radius: 20 # used if gicp_normal_use_knn_search = false
gicp_normal_search_k_neighbours: 20 # used if gicp_normal_use_knn_search = true
gicp_info_diag: [1e8, 1e8, 1e8, 1e8]

# DR weights - uncertainty on vehicle navigation across submap
dr_noise_x: 5.
dr_noise_y: 5.
dr_noise_z: 1.
dr_noise_roll: 1e-2
dr_noise_pitch: 1e-2
dr_noise_yaw: 1e-1

# Loop closure edge covariance computation method
# 0 = fixed external value
# 1 = manual inputs (#TODO: factor out to YAML file)
# 2 = covariances from GICP
# 3 = covariances loaded from external file
lc_edge_covs_type: 2
